version: '3.8'
services:
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_node
    ports:
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - "C:/ipfs:/data/ipfs"  # Local path to IPFS data, adjust based on your system
    restart: always
    environment:
      - IPFS_PATH=/data/ipfs  # Ensure IPFS uses the volume path for data
    networks:
      - local_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "5000:5000"  # Backend API
    volumes:
      - ./backend:/app
    depends_on:
      - ipfs
    restart: always
    networks:
      - local_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:5173"  # Frontend port
    depends_on:
      - backend
    restart: always
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
