version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Points to your Dockerfile
    volumes:
      - ./backend:/usr/src/app  # This maps the local backend directory to the container
    ports:
      - "5000:5000"  # Exposing port 5000 for the backend
    command: ["npm", "run", "dev"]  # Runs 'nodemon' when container starts
    environment:
      - NODE_ENV=development  # Optional: set the environment to development

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_node
    volumes:
      - ipfs_data:/data/ipfs  # Persist IPFS data across container restarts
    ports:
      - "5001:5001"  # Expose IPFS API port
      - "8080:8080"  # Expose IPFS Gateway port
    restart: always
    environment:
      - IPFS_PATH=/data/ipfs  # Ensure IPFS uses the volume path for data

volumes:
  ipfs_data:  # Define volume for IPFS data
